version: '3.7'

services:
     
  redis-master:
    image: redis:7-alpine
    command: "redis-server /etc/redis/master.conf"
    volumes:
      - "~/.redis-master-data:/data"
      - ~/properties:/etc/redis
    ports:
      - "26379:26379"
 
  redis-slave:
    image: redis:7-alpine
    command: redis-server /etc/redis/slave.conf --slaveof redis-master 26379
    volumes:
      - "~/.redis-slave-data:/data"
      - ~/properties:/etc/redis
    ports:
      - "26380:26380"
     
  # Instance 1
  redis-sentinel:
    image: redis:7-alpine
    command: redis-server /etc/redis/sentinel1.conf --sentinel
    volumes:
      - "~/.redis-sentinel1-data:/data"
      - ~/properties:/etc/redis
    ports:
      - 26381:26381
 
  # Instance 2
  redis-sentinel2:
    image: redis:7-alpine
    command: redis-server /etc/redis/sentinel2.conf --sentinel
    volumes:
      - "~/.redis-sentinel2-data:/data"
      - ~/properties:/etc/redis
    ports:
      - 26382:26382
 
  # Instance 3
  redis-sentinel3:
    image: redis:7-alpine
    command: redis-server /etc/redis/sentinel3.conf --sentinel
    volumes:
      - "~/.redis-sentinel3-data:/data"
      - ~/properties:/etc/redis
    ports:
      - 26383:26383
