version: '3.7'

services:
 
#  app:
#    image: some-image
#    links:
#      - redis-sentinel
     
  redis-master:
    image: redis:7-alpine
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - "./.data:/data"
      - ~/properties:/etc/redis
    ports:
      - "6379:6379"
 
  redis-slave:
    image: redis:7-alpine
    command: ["redis-server", "/etc/redis/master-redis.conf"]
    volumes:
      - "./.data:/data"
      - ~/properties:/etc/redis
    ports:
      - "6380:6380"
     
  # Instance 1
  redis-sentinel:
    build: 
      context: ./redis-sentinel1
    volumes:
      - ~/properties:/etc/redis
    ports:
      - 26379:26379
 
  # Instance 2
  redis-sentinel2:
    build: 
      context: ./redis-sentinel2
    volumes:
      - ~/properties:/etc/redis
    ports:
      - 26380:26380
 
  # Instance 3
  redis-sentinel3:
    build: 
      context: ./redis-sentinel3
    volumes:
      - ~/properties:/etc/redis
    ports:
      - 26381:26381
